### PR TITLE
Create Peering for BridgeServer2 Develop VPC

### PR DESCRIPTION
**Pull request by DwayneJengSage**
Need to create VPC for Bridge Dev AWS account. This involves creating VPC peering.

### CODE REVIEW

**Comment by ahayden** [comment]
I verified the inputs are correct, but if there's no rush let's wait to Khai so we can sure nothing is missing for the automation to work

**Review by xschildw — APPROVED** [review]
Looks good to me, it should work like the other ones.

**Review by zaro0508 — APPROVED** [review]

**Comment by DwayneJengSage** [comment]
Hi. I'm ready to merge this. Thanks!

**Comment by DwayneJengSage** [comment]
@ahayden @zaro0508 @xschildw Can we merge this now? We need access to the DBs we're creating in the Bridge Dev account. At this point, we can work around lack of access by deleting and recreating the database instance, but this will become a sprint blocker very very soon. Thanks!

**Comment by DwayneJengSage** [comment]
Update: Apparently, deleting the database requires me to delete and recreate both the BridgeServer and DB stacks, which is a very expensive and time-consuming process. As such, this is now a sprint blocker and blocks completion of security task https://sagebionetworks.jira.com/browse/BRIDGE-1931

Filing https://sagebionetworks.jira.com/browse/IT-1053 to make sure this is tracked.

**Pull request merged**
